[2023-01-04T11:52:07.926+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T11:44:45.945458+00:00 [queued]>
[2023-01-04T11:52:07.936+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T11:44:45.945458+00:00 [queued]>
[2023-01-04T11:52:07.936+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T11:52:07.937+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-01-04T11:52:07.937+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T11:52:07.953+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-04 11:44:45.945458+00:00
[2023-01-04T11:52:07.958+0000] {standard_task_runner.py:55} INFO - Started process 1767 to run task
[2023-01-04T11:52:07.961+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-04T11:44:45.945458+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmps6t2dbeo']
[2023-01-04T11:52:07.963+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask load_to_postgres
[2023-01-04T11:52:08.024+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T11:44:45.945458+00:00 [running]> on host 523cb283ca0d
[2023-01-04T11:52:08.098+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T11:44:45.945458+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T11:44:45.945458+00:00
[2023-01-04T11:52:08.996+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-04T11:53:04.781+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T11:53:04.789+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=load_to_postgres, execution_date=20230104T114445, start_date=20230104T115207, end_date=20230104T115304
[2023-01-04T11:53:04.909+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T11:53:04.925+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
