[2023-01-04T12:04:53.444+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T12:04:51.699059+00:00 [queued]>
[2023-01-04T12:04:53.455+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T12:04:51.699059+00:00 [queued]>
[2023-01-04T12:04:53.455+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:04:53.456+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T12:04:53.457+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:04:53.470+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_clean_transform_dataset_task> on 2023-01-04 12:04:51.699059+00:00
[2023-01-04T12:04:53.474+0000] {standard_task_runner.py:55} INFO - Started process 3416 to run task
[2023-01-04T12:04:53.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'extract_clean_transform_dataset_task', 'manual__2023-01-04T12:04:51.699059+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmpf02w8bxb']
[2023-01-04T12:04:53.479+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask extract_clean_transform_dataset_task
[2023-01-04T12:04:53.543+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task manual__2023-01-04T12:04:51.699059+00:00 [running]> on host 523cb283ca0d
[2023-01-04T12:04:53.615+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_clean_transform_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T12:04:51.699059+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T12:04:51.699059+00:00
[2023-01-04T12:04:54.840+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:289 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T12:05:09.248+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:116 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T12:05:09.278+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:125 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T12:05:09.651+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/utils/validation.py:993 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2023-01-04T12:06:05.914+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T12:06:05.929+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=extract_clean_transform_dataset_task, execution_date=20230104T120451, start_date=20230104T120453, end_date=20230104T120605
[2023-01-04T12:06:05.980+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T12:06:06.005+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
