[2023-01-04T12:06:37.493+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T12:04:51.699059+00:00 [queued]>
[2023-01-04T12:06:37.504+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T12:04:51.699059+00:00 [queued]>
[2023-01-04T12:06:37.505+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:06:37.505+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T12:06:37.524+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:06:37.564+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-04 12:04:51.699059+00:00
[2023-01-04T12:06:37.569+0000] {standard_task_runner.py:55} INFO - Started process 3647 to run task
[2023-01-04T12:06:37.572+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-04T12:04:51.699059+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmp0slwa4af']
[2023-01-04T12:06:37.574+0000] {standard_task_runner.py:83} INFO - Job 32: Subtask load_to_postgres
[2023-01-04T12:06:37.650+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.load_to_postgres manual__2023-01-04T12:04:51.699059+00:00 [running]> on host 523cb283ca0d
[2023-01-04T12:06:37.738+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T12:04:51.699059+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T12:04:51.699059+00:00
[2023-01-04T12:06:38.912+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-04T12:07:36.185+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T12:07:36.193+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=load_to_postgres, execution_date=20230104T120451, start_date=20230104T120637, end_date=20230104T120736
[2023-01-04T12:07:36.301+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T12:07:36.317+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
