[2023-01-04T16:02:37.172+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [queued]>
[2023-01-04T16:02:37.182+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [queued]>
[2023-01-04T16:02:37.183+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:02:37.183+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T16:02:37.184+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T16:02:37.203+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2023-01-04 15:59:24.331300+00:00
[2023-01-04T16:02:37.208+0000] {standard_task_runner.py:55} INFO - Started process 711 to run task
[2023-01-04T16:02:37.211+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'create_dashboard_task', 'manual__2023-01-04T15:59:24.331300+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmphx4a23rq']
[2023-01-04T16:02:37.213+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask create_dashboard_task
[2023-01-04T16:02:37.287+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.create_dashboard_task manual__2023-01-04T15:59:24.331300+00:00 [running]> on host 4de77850e514
[2023-01-04T16:02:37.373+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-04T15:59:24.331300+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-04T15:59:24.331300+00:00
[2023-01-04T16:02:39.041+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T16:02:40.197+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2023-01-04T16:02:40.197+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2023-01-04T16:02:40.204+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-04T16:02:40.205+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-04T16:02:40.206+0000] {logging_mixin.py:137} WARNING - Address already in use
[2023-01-04T16:02:40.207+0000] {logging_mixin.py:137} WARNING - Port 8050 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2023-01-04T16:02:40.274+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T16:02:40.294+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
