[2023-01-04T11:34:45.882+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-04T11:34:45.895+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-04T11:34:45.896+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T11:34:45.896+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-04T11:34:45.897+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T11:34:45.914+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_clean_transform_dataset_task> on 2023-01-02 00:00:00+00:00
[2023-01-04T11:34:45.920+0000] {standard_task_runner.py:55} INFO - Started process 296 to run task
[2023-01-04T11:34:45.929+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_etl_pipeline', 'extract_clean_transform_dataset_task', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/accidents_etl.py', '--cfg-path', '/tmp/tmp6bb7qzpw']
[2023-01-04T11:34:45.933+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask extract_clean_transform_dataset_task
[2023-01-04T11:34:46.031+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_etl_pipeline.extract_clean_transform_dataset_task scheduled__2023-01-02T00:00:00+00:00 [running]> on host 523cb283ca0d
[2023-01-04T11:34:46.135+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=extract_clean_transform_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-04T11:34:47.784+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:289 DtypeWarning: Columns (35) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-01-04T11:35:03.937+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:116 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T11:35:03.973+0000] {logging_mixin.py:137} WARNING - /opt/***/dags/Milestone3_1.py:125 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-04T11:35:04.477+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/utils/validation.py:993 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2023-01-04T11:36:10.006+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-04T11:36:10.023+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=accidents_etl_pipeline, task_id=extract_clean_transform_dataset_task, execution_date=20230102T000000, start_date=20230104T113445, end_date=20230104T113610
[2023-01-04T11:36:10.091+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-04T11:36:10.108+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
